
export const HEBREW_TEXT = {
  appName: "Join us",
  auth: {
    signIn: "התחברות",
    signUp: "הרשמה",
    signOut: "התנתקות",
    email: "אימייל",
    password: "סיסמה",
    signInWithGoogle: "התחבר עם גוגל",
    signInWithApple: "התחבר עם אפל",
    signInWithPhone: "התחבר עם מספר טלפון",
    signUpWithPhone: "הירשם עם מספר טלפון",
    phoneNumber: "מספר טלפון",
    phoneNumberPlaceholderShort: "05X-XXXXXXX",
    sendOtp: "שלח קוד",
    otpCode: "קוד אימות",
    verifyOtp: "אמת קוד",
    alreadyHaveAccount: "כבר יש לך חשבון? התחבר",
    noAccount: "אין לך חשבון? הירשם",
    forgotPassword: "שכחת סיסמה?",
    signInButton: "התחבר",
    signUpButton: "הירשם",
    emailInvalid: "אנא הכנס כתובת אימייל תקינה.",
    passwordMinLengthError: "סיסמה חייבת להכיל לפחות 6 תווים.",
    emailInUseError: "כתובת אימייל זו כבר רשומה.",
    weakPasswordError: "הסיסמה חלשה מדי. נסה סיסמה חזקה יותר.",
    invalidPhoneNumber: "מספר טלפון לא תקין. אנא השתמש בפורמט +972XXXXXXXXX.",
    invalidIsraeliPhoneNumber: "מספר טלפון ישראלי לא תקין. חייב להיות בן 10 ספרות ולהתחיל ב-05.",
    otpSent: "קוד אימות נשלח למספר הטלפון שלך.",
    otpError: "שגיאה בשליחת קוד האימות. אנא נסה שוב.",
    invalidOtp: "קוד האימות שגוי. אנא נסה שוב.",
    phoneSignInSuccess: "התחברת בהצלחה!",
    phoneSignUpSuccess: "נרשמת בהצלחה!",
    recaptchaError: "שגיאה באימות reCAPTCHA. נסה לרענן את הדף או נסה שוב מאוחר יותר.",
    phoneOrEmail: "או התחבר/הירשם עם",
    switchToEmail: "התחברות עם אימייל וסיסמה",
    switchToPhone: "התחברות עם מספר טלפון",
  },
  navigation: {
    home: "דף הבית",
    events: "אירועים",
    createEvent: "פרסום",
    profile: "פרופיל",
    leaderboard: "טבלת מובילים",
    mobileMenuTitle: "תפריט",
    messages: "בקשות",
  },
  event: {
    createEventTitle: "יצירת אירוע חדש",
    editEvent: "ערוך אירוע",
    eventName: "שם האירוע",
    eventNameDisplayPlaceholder: "שם האירוע שלכם",
    eventNameGenericPlaceholder: "אירוע",
    eventNameMinLengthError: "שם האירוע חייב להכיל לפחות 2 תווים.",
    numberOfGuests: "סה\"כ מקומות",
    availableSpots: "מקומות פנויים",
    pricePerGuest: "מחיר לאורח",
    paymentOptions: "אפשרויות תשלום",
    payWhatYouWant: "שלם כפי יכולתך",
    free: "חינם",
    location: "מיקום",
    dateTime: "תאריך",
    selectDate: "בחר תאריך",
    description: "תיאור",
    ageRange: "טווח גילאים",
    foodType: "סוג כיבוד", 
    meat: "בשרי",
    dairy: "חלבי",
    meatAndDairy: "בשרי + חלבי",
    vegetarian: "צמחוני",
    vegan: "טבעוני",
    kosherParve: "כשר פרווה",
    kashrut: "כשרות",
    kosher: "כשר",
    notKosher: "ללא כשרות", 
    weddingType: "סוג חתונה", 
    traditional: "מסורתית",
    civil: "אזרחית",
    harediWithSeparation: "חרדית עם הפרדה",
    religionStyle: "סגנון דתי", 
    uploadImage: "העלאת תמונה",
    createEventButton: "צור אירוע",
    discoverEvents: "גלה אירועים",
    filters: "סנן",
    filterButtonAppliedText: "סינון",
    applyFilters: "החל סננים",
    filterByLocation: "סינון לפי מיקום",
    filterByTime: "סינון לפי זמן",
    filterByPrice: "סינון לפי מחיר",
    filterByType: "סינון לפי סוג",
    joinEvent: "הצטרף לאירוע",
    requestToJoin: "בקש להצטרף",
    cancelRequest: "בטל בקשה",
    viewRequests: "צפה בבקשות",
    approve: "אשר",
    reject: "דחה",
    guestRequests: "בקשות אורחים",
    approvedGuests: "אורחים מאושרים",
    noApprovedGuests: "אין אורחים מאושרים עדיין.",
    noPendingRequests: "אין בקשות הצטרפות ממתינות.",
    rateGuest: "דרג אורח",
    broadcastMessage: "שלח הודעה לכל האורחים",
    eventDetails: "פרטי אירוע",
    myEvents: "האירועים בבעלותי",
    upcomingEvents: "אירועים קרובים",
    pastEvents: "אירועים קודמים",
    noEventsFound: "לא נמצאו אירועים",
    noEventsFoundMessage: "לא נמצאו אירועים התואמים את החיפוש.",
    noUsersFound: "לא נמצאו משתמשים.",
    noSpotsAvailableTitle: "אין מקומות פנויים",
    noSpotsAvailableMessage: "לא נותרו מקומות פנויים באירוע זה.",
    noSpotsAvailableShort: "אזלו",
    confirmAttendance: "אישור הגעה",
    didNotAttend: "לא השתתף",
    automaticNegativeReview: "ביקורת שלילית אוטומטית תירשם עקב אי-הגעה.",
    deleteEvent: "מחק אירוע",
    deleteConfirmationTitle: "אישור מחיקת אירוע",
    deleteConfirmationMessage: "האם אתה בטוח שברצונך למחוק אירוע זה? פעולה זו אינה ניתנת לשחזור.",
    eventDeletedSuccessfully: "האירוע נמחק בהצלחה.",
    errorDeletingEvent: "שגיאה במחיקת האירוע.",
    errorDeletingImageFromStorage: "שגיאה במחיקת תמונת האירוע מהאחסון. התמונה עשויה עדיין להתקיים בשרת. בדוק הרשאות אחסון.",
    owners: "בעלי האירוע",
    addOwner: "הוסף בעלים",
    searchUsersPlaceholder: "חפש משתמשים לפי שם או אימייל...",
    userAlreadyOwner: "משתמש זה כבר מוגדר כבעלים.",
    add: "הוסף",
    removeOwner: "הסר בעלות",
    confirmRemoveOwnerTitle: "אישור הסרת בעלות",
    confirmRemoveOwnerMessage: "האם אתה בטוח שברצונך להסיר את {userName} מבעלי האירוע?",
    cannotRemoveSelf: "אינך יכול להסיר את עצמך אם אתה הבעלים היחיד.",
    cannotRemoveLastOwner: "לא ניתן להסיר את הבעלים האחרון של האירוע.",
    dateTimeRequiredError: "תאריך ושעת האירוע הם שדה חובה.",
    dateTimeInFutureError: "תאריך ושעת האירוע חייבים להיות בעתיד.",
    selectDateTimePlaceholder: "בחר תאריך ושעה",
    minAvailableSpotsFilterLabel: "מינימום מקומות פנויים",
    noApprovedGuestsYet: "אין אורחים מאושרים עדיין.",
    shareEventTitle: "שתף אירוע",
    eventSharedSuccessfully: "האירוע שותף בהצלחה!",
    errorSharingEvent: "שגיאה בשיתוף האירוע. נסה שוב מאוחר יותר.",
    linkCopiedToClipboard: "הקישור הועתק ללוח!",
    errorCopyingLink: "שגיאה בהעתקת הקישור.",
    checkOutEvent: "בדוק את האירוע הזה",
    manageGuestsTitle: "ניהול אורחים",
    manageGuestsPageTitle: "ניהול אורחי האירוע",
    exportToCsv: "יצא ל-CSV",
    exportingGuests: "מייצא רשימת אורחים...",
    guestsExportedSuccessfully: "רשימת האורחים יוצאה בהצלחה!",
    errorExportingGuests: "שגיאה ביצוא רשימת האורחים.",
    noGuestsToExport: "אין אורחים מאושרים לייצוא.",
    guestList: "רשימת אורחים",
    broadcastAnnouncements: "הודעות לכלל האורחים",
    latestAnnouncements: "הודעות אחרונות",
    sendNewAnnouncement: "שלח הודעה חדשה",
    announcementMessagePlaceholder: "כתוב את הודעתך כאן...",
    sendAnnouncement: "שלח הודעה",
    announcementSentSuccessfully: "ההודעה נשלחה בהצלחה לכל האורחים המאושרים.",
    errorSendingAnnouncement: "שגיאה בשליחת ההודעה.",
    noAnnouncementsYet: "עדיין לא נשלחו הודעות לאורחים.",
    announcementBy: "נשלח על ידי:",
    fullName: "שם מלא",
    phone: "טלפון",
    age: "גיל",
    revokeApproval: "בטל אישור הגעה",
    confirmRevokeApprovalTitle: "אישור ביטול הגעה",
    confirmRevokeApprovalMessage: "האם אתה בטוח שברצונך לבטל את אישור ההגעה של {guestName}?",
    revokeConsequenceMessage: "פעולה זו תסגור את הצ'אט ותסמן את בקשתם כנדחית.",
    confirmRevoke: "אשר ביטול",
    guestApprovalRevoked: "אישור ההגעה של {guestName} בוטל.",
    errorRevokingApproval: "שגיאה בביטול אישור ההגעה.",
  },
  profile: {
    userProfile: "פרופיל משתמש",
    editProfile: "עריכת פרופיל",
    name: "שם",
    birthday: "תאריך לידה",
    age: "גיל",
    yearsOldSuffix: "שנים",
    ageNotProvided: "גיל לא סופק",
    infoNotProvided: "לא סופק",
    bioNotProvided: "לא סופק ביו.",
    uploadProfileImage: "העלה תמונת פרופיל",
    bio: "קצת עליי",
    phone: "טלפון (אופציונלי)",
    email: "אימייל",
    uploadIdForVerification: "העלה תעודת זהות (לאימות)",
    verifiedBadge: "מאומת",
    verificationPending: "אימות בתהליך",
    pastEventsAttended: "אירועים קודמים שהשתתפת",
    reviews: "ביקורות",
    saveChanges: "שמור שינויים",
    settings: "הגדרות",
    darkMode: "מצב כהה",
    lightMode: "מצב בהיר",
    nameMinLengthError: "שם חייב להכיל לפחות 2 תווים.",
    birthdayRequiredError: "תאריך לידה הוא שדה חובה.",
    noFutureEventsOwned: "ל{name} אין אירועים עתידיים בבעלותו כרגע.",
    noFutureEventsOwnedSelf: "לך אין אירועים עתידיים בבעלותך כרגע.",
    legalInformationSectionTitle: "מידע משפטי",
    termsOfUseLink: "תנאי שימוש",
    privacyPolicyLink: "מדיניות פרטיות",
  },
  notifications: {
    title: "התראות",
    eventApproved: "בקשתך להצטרף לאירוע אושרה!",
    eventUpdated: "עדכון לגבי אירוע",
    newMessage: "הודעה חדשה",
    eventReminder: "תזכורת לאירוע",
    markAsRead: "סמן כנקרא",
    noNotifications: "אין התראות חדשות.",
  },
  chat: {
    title: "צ'אט",
    myRequests: "הבקשות שלי",
    eventsInMyOwnership: "אירועים בבעלותי",
    requestToJoinEventTitle: "בקשה להצטרפות לאירוע",
    introduceYourselfPlaceholder: "ספרו קצת על עצמכם ולמה תרצו להצטרף...",
    sendRequest: "שלח בקשה וצור צ'אט",
    messageToOwners: "הודעה לבעלי האירוע",
    chatCreatedSuccessfully: "הצ'אט נוצר בהצלחה, הנך מועבר...",
    errorCreatingChat: "שגיאה ביצירת הצ'אט.",
    errorFetchingChat: "שגיאה בטעינת הצ'אט.",
    chatAlreadyExists: "כבר פתחת צ'אט לאירוע זה. הנך מועבר אליו...",
    typeYourMessage: "הקלד/י הודעה...",
    sendMessage: "שלח",
    acceptRequest: "אשר בקשה",
    declineRequest: "דחה בקשה",
    requestAccepted: "הבקשה אושרה!",
    requestDeclined: "הבקשה נדחתה.",
    statusPending: "ממתין לאישור בעלי האירוע",
    statusActive: "פעיל",
    statusApproved: "הבקשה אושרה",
    statusRejected: "הבקשה נדחתה",
    statusClosed: "סגור",
    noMessagesYet: "אין הודעות עדיין. התחל/י את השיחה!",
    chatWith: "שיחה עם",
    chatWithGuest: "צ'אט עם האורח",
    guest: "אורח",
    eventOwner: "בעל אירוע",
    you: "אתה",
    startChatPrompt: "נראה שעדיין לא התחלת צ'אט עבור אירוע זה. כתוב הודעת פתיחה לבעלי האירוע:",
    messageRequired: "הודעה נדרשת.",
    noChatsFound: "לא נמצאו צ'אטים התואמים את הסינון הנוכחי.",
    noChatsFoundOwner: "אין בקשות הצטרפות לאירועים שבבעלותך התואמות את הסינון הנוכחי.",
    noChatsFoundGuest: "לא ביקשת להצטרף לאירועים התואמים את הסינון הנוכחי.",
    noFutureOwnedChats: "אין בקשות הצטרפות לאירועים עתידיים שבבעלותך.",
    noPastOwnedChats: "אין בקשות הצטרפות לאירועים קודמים שבבעלותך.",
    noFutureRequestedChats: "לא ביקשת להצטרף לאירועים עתידיים.",
    noPastRequestedChats: "לא ביקשת להצטרף לאירועים קודמים.",
    loadingChats: "טוען צ'אטים...",
    confirmDeclineRequestTitle: "אישור דחיית בקשה",
    confirmDeclineRequestMessage: "האם אתה בטוח שברצונך לדחות את בקשת ההצטרפות של {guestName}?",
    confirmCloseChatTitle: "אישור סגירת צ'אט",
    confirmCloseChatMessages: "האם אתה בטוח שברצונך לסגור צ'אט זה? לא ניתן יהיה לשלוח הודעות נוספות.",
    chatClosed: "צ'אט זה נסגר.",
    chatClosedByOwner: "צ'אט זה נסגר על ידי בעל האירוע.",
    viewChat: "צפה בצ'אט",
    lastMessage: "הודעה אחרונה",
    unread: "לא נקראו",
    errorFetchingChats: "שגיאה בטעינת הצ'אטים. נסה שוב מאוחר יותר.",
    errorFetchingFutureEvents: "שגיאה בטעינת אירועים עתידיים שבבעלותך.",
    messagesPageTitle: "ההודעות שלי",
    chatPageTitle: "פרטי שיחה",
    loadingChatDetails: "טוען פרטי שיחה...",
    errorFetchingMessages: "שגיאה בטעינת הודעות.",
    failedToSendMessage: "שליחת ההודעה נכשלה.",
    messageSent: "ההודעה נשלחה.",
    requestManagement: "ניהול בקשה",
    chatClosedInfo: "שיחה זו נסגרה. לא ניתן לשלוח הודעות נוספות.",
    requestRejectedInfo: "בקשת ההצטרפות נדחתה. לא ניתן לשלוח הודעות נוספות.",
    requestApprovedMessage: "הבקשה להצטרפות לאירוע אושרה!",
    requestDeclinedMessage: "הבקשה להצטרפות לאירוע נדחתה.",
    chatClosedMessage: "השיחה נסגרה.",
    closeChat: "סגור שיחה",
    confirmAction: "אישור פעולה",
    confirmCloseChatMessage: "האם אתה בטוח שברצונך לסגור שיחה זו?",
    chatTimeFilter: "סנן לפי זמן אירוע",
    allChats: "כל השיחות",
    futureEventChats: "שיחות לאירועים עתידיים",
    pastEventChats: "שיחות לאירועים שעברו",
    statusPendingDisplayGuest: "בקשתך ממתינה",
    statusPendingDisplayOwner: "בהמתנה",
    statusApprovedDisplay: "אושרה",
    statusRejectedDisplay: "נדחתה",
    statusActiveDisplay: "פעילה",
    statusClosedDisplay: "סגורה",
    chatStatusFilter: "סנן לפי סטטוס שיחה",
    allStatuses: "כל הסטטוסים",
    pendingRequests: "בקשות ממתינות",
    approvedRequests: "בקשות שאושרו",
    activeChats: "שיחות פעילות",
    rejectedRequests: "בקשות שנדחו",
    closedChats: "שיחות שנסגרו",
  },
  general: {
    loading: "טוען...",
    error: "אירעה שגיאה",
    success: "הפעולה בוצעה בהצלחה",
    close: "סגור",
    optional: "אופציונלי",
    search: "חיפוש...",
    searchEventsSimplePlaceholder: "חיפוש חופשי (שם, מקום, תיאור...)",
    searchEventsSpecificPlaceholder: "יוגה, פילאטיס, מסאז'...",
    actions: "פעולות",
    details: "פרטים",
    back: "חזור",
    welcome: "ברוכים הבעים ל",
    appDescription: "פלטפורמה המחברת בין זוגות מארגני חתונות לבין אורחים המחפשים מקומות פנויים ברגע האחרון. עזרו לזוגות להימנע מהפסדים כספיים ומצאו לעצמכם מקום באירוע במחיר הוגן.",
    forCouples: "לזוגות",
    forGuests: "לאורחים",
    createYourEvent: "צרו את האירוע שלכם",
    findOpenSpots: "מצאו מקומות פנויים",
    to: "ל",
    tryAgainLater: "נסו לשנות את תנאי הסינון או בדקו שוב מאוחר יותר.",
    clearFilters: "נקה סננים",
    next: "הבא",
    previous: "הקודם",
    getStarted: "התחבר והתחל",
    howItWorks: "איך זה עובד?",
    delete: "מחק",
    cancel: "ביטול",
    confirm: "אישור",
    formValidationFailed: "אנא מלא את כל שדות החובה ותקן את השגיאות המסומנות.",
    yesterday: "אתמול",
  },
  foodIcons: {
    kosherMeat: "בשרי", 
    kosherDairy: "חלבי",
    kosherParve: "פרווה",
    notKosher: "לא כשר",
  },
  emojis: {
    thumbsUp: "👍",
    thumbsDown: "👎",
  },
  map: {
    title: "מפת אירועים",
    searchOnMapTitle: "חיפוש במפה",
    eventsOnMap: "אירועים על המפה",
    fetchingLocation: "מאחזר מיקום נוכחי...",
    locationError: "שגיאה באחזור המיקום. אנא ודא שהרשאות המיקום מאופשרות בדפדפן.",
    geolocationNotSupported: "שירותי מיקום אינם נתמכים בדפדפן זה.",
    yourLocationMarker: "המיקום שלך",
    eventLocationMarker: "מיקום האירוע",
    apiKeyMissing: "מפתח ה-API של גוגל מפות חסר. המפה לא יכולה להיטען.",
    loadError: "שגיאה בטעינת גוגל מפות. נסה לרענן את הדף.",
    errorTitle: "שגיאת מפה",
    errorTitleShort: "שגיאה",
    locationUnavailable: "המיקום אינו זמין.",
    yourCurrentLocation: "המיקום הנוכחי שלך:",
    latitude: "קו רוחב",
    longitude: "קו אורך",
    openFullMap: "פתח מפה מלאה",
  },
  legal: {
    privacyPolicyTitle: "מדיניות פרטיות",
    termsOfUseTitle: "תנאי שימוש",
  }
};
    
