export const HEBREW_TEXT = {
  appName: "Join us",
  auth: {
    signIn: "התחברות",
    signUp: "הרשמה",
    signOut: "התנתקות",
    email: "אימייל",
    password: "סיסמה",
    signInWithGoogle: "התחבר עם גוגל",
    signInWithApple: "התחבר עם אפל",
    alreadyHaveAccount: "כבר יש לך חשבון? התחבר",
    noAccount: "אין לך חשבון? הירשם",
    forgotPassword: "שכחת סיסמה?",
    signInButton: "התחבר",
    signUpButton: "הירשם",
  },
  navigation: {
    home: "דף הבית",
    events: "אירועים",
    createEvent: "יצירת אירוע",
    profile: "פרופיל",
    leaderboard: "טבלת מובילים",
  },
  event: {
    createEventTitle: "יצירת אירוע חדש",
    eventName: "שם האירוע",
    numberOfGuests: "מספר אורחים",
    pricePerGuest: "מחיר לאורח",
    paymentOptions: "אפשרויות תשלום",
    payWhatYouWant: "שלם כפי יכולתך",
    free: "חינם",
    location: "מיקום",
    dateTime: "תאריך ושעה",
    selectDate: "בחר תאריך",
    description: "תיאור",
    ageRange: "טווח גילאים",
    foodType: "סוג אוכל",
    kosherMeat: "כשר בשרי",
    kosherDairy: "כשר חלבי",
    kosherParve: "כשר פרווה",
    notKosher: "לא כשר",
    religionStyle: "סגנון דתי",
    uploadImage: "העלאת תמונה",
    createEventButton: "צור אירוע",
    discoverEvents: "גלה אירועים",
    filters: "סינון",
    filterByLocation: "סינון לפי מיקום",
    filterByTime: "סינון לפי זמן",
    filterByPrice: "סינון לפי מחיר",
    filterByType: "סינון לפי סוג",
    joinEvent: "הצטרף לאירוע",
    requestToJoin: "בקש להצטרף",
    cancelRequest: "בטל בקשה",
    viewRequests: "צפה בבקשות",
    approve: "אשר",
    reject: "דחה",
    guestRequests: "בקשות אורחים",
    approvedGuests: "אורחים מאושרים",
    noApprovedGuests: "אין אורחים מאושרים עדיין.",
    noPendingRequests: "אין בקשות הצטרפות ממתינות.",
    rateGuest: "דרג אורח",
    broadcastMessage: "שלח הודעה לכל האורחים",
    eventDetails: "פרטי אירוע",
    myEvents: "האירועים שלי",
    upcomingEvents: "אירועים קרובים",
    pastEvents: "אירועים קודמים",
    noEventsFound: "לא נמצאו אירועים התואמים את החיפוש.",
    confirmAttendance: "אישור הגעה",
    didNotAttend: "לא השתתף",
    automaticNegativeReview: "ביקורת שלילית אוטומטית תירשם עקב אי-הגעה.",
  },
  profile: {
    userProfile: "פרופיל משתמש",
    editProfile: "עריכת פרופיל",
    name: "שם",
    birthday: "תאריך לידה",
    uploadProfileImage: "העלה תמונת פרופיל",
    bio: "קצת עליי",
    phone: "טלפון",
    email: "אימייל",
    uploadIdForVerification: "העלה תעודת זהות (לאימות)",
    verifiedBadge: "מאומת",
    verificationPending: "אימות בתהליך",
    pastEventsAttended: "אירועים קודמים שהשתתפת",
    reviews: "ביקורות",
    saveChanges: "שמור שינויים",
  },
  notifications: {
    title: "התראות",
    eventApproved: "בקשתך להצטרף לאירוע אושרה!",
    eventUpdated: "עדכון לגבי אירוע",
    newMessage: "הודעה חדשה",
    eventReminder: "תזכורת לאירוע",
    markAsRead: "סמן כנקרא",
    noNotifications: "אין התראות חדשות.",
  },
  general: {
    loading: "טוען...",
    error: "אירעה שגיאה",
    success: "הפעולה בוצעה בהצלחה",
    close: "סגור",
    optional: "אופציונלי",
    search: "חיפוש...",
    actions: "פעולות",
    details: "פרטים",
    back: "חזור",
    welcome: "ברוכים הבאים ל",
    appDescription: "פלטפורמה המחברת בין זוגות מארגני חתונות לבין אורחים המחפשים מקומות פנויים ברגע האחרון. עזרו לזוגות להימנע מהפסדים כספיים ומצאו לעצמכם מקום באירוע במחיר הוגן.",
    forCouples: "לזוגות",
    forGuests: "לאורחים",
    createYourEvent: "צרו את האירוע שלכם",
    findOpenSpots: "מצאו מקומות פנויים",
    to: "ל",
  },
  foodIcons: {
    // Using text for clarity as specific kosher icons are hard to standardize
    kosherMeat: "בשרי",
    kosherDairy: "חלבי",
    kosherParve: "פרווה",
    notKosher: "לא כשר",
  },
  emojis: {
    thumbsUp: "👍",
    thumbsDown: "👎",
  }
};
